# Generated by Django 5.1.1 on 2024-10-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
